In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 11

In [2]:
n = 4
a = np.zeros((n, n))
#a[0,0] = 1
for j in range(0, n):
    for i in range(j, j+1):
       # while 
        a[i, j] = i + j
print(a)

[[0. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 6.]]


In [3]:
n = 4
a = np.zeros((n, n))
for j in range(0, n):
    for i in range(0, 1):
        num = 0
        a[i, j] = 0
        while num<j+1:
            a[i, j] += 1
            num += 1
for i in range(1, n):
    for j in range(3, 4):
        num = 4
        a[i, j] = 4
        while num< i+4:
            a[i, j] += 1
            num += 1
for j in range(3, -1, -1):
    for i in range(3, 4):
        num = 7
        a[i, j] = 10
        while num< j+7:
            a[i, j] -= 1
            num += 1

a

array([[ 1.,  2.,  3.,  4.],
       [ 0.,  0.,  0.,  5.],
       [ 0.,  0.,  0.,  6.],
       [10.,  9.,  8.,  7.]])

In [4]:
n = 4
a = np.zeros((n, n))
for j in range(0, n):
    for i in range(0, 1):
        num = 0
        a[i, j] = 0
        while num<j+1:
            a[i, j] += 1
            num += 1
for i in range(1, n):
    for j in range(3, 4):
        num = 4
        a[i, j] = 4
        while num< i+4:
            a[i, j] += 1
            num += 1
for j in range(3, -1, -1):
    for i in range(3, 4):
        num = 7
        a[i, j] = 10
        while num< j+7:
            a[i, j] -= 1
            num += 1
for i in range(2, 0, -1):
    for j in range(0, 1):
        num = 10
        a[i, j] = 12
        while num< i+9:
            a[i, j] -= 1
            num += 1
for j in range(1, 3):
    for i in range(1, 2):
        num = 12
        a[i, j] = 12
        while num< j+12:
            a[i, j] += 1
            num += 1
for i in range(2, 3):
    for j in range(2, 3):
        num = 14
        a[i, j] = 14
        while num< i+13:
            a[i, j] += 1
            num += 1
for j in range(1, 0, -1):
    for i in range(2, 3):
        num = 15
        a[i, j] = 16
        while num< j+14:
            a[i, j] -= 1
            num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [12., 13., 14.,  5.],
       [11., 16., 15.,  6.],
       [10.,  9.,  8.,  7.]])